version: "3"
services:
  server:
    restart: always
    env_file: .env
    build: server
    tty: true
    ports:
      - "22005:22005/udp"
      - "22006:22006"
    depends_on:
      - cache
    volumes:
      - ../core:/app/core
      - ../server:/app/server
      - ../cache:/app/cache
      - ../databases:/app/databases
  cache:
    restart: always
    env_file: .env
    build: cache
    ports:
      - 2630:2630
    volumes:
      - ../core:/app/core
      - ../server:/app/server
      - ../cache:/app/cache
      - ../databases:/app/databases
