version: "3.7"
services:
  api:
    restart: always
    env_file: docker.env
    build: server
    tty: true
    platform: linux/x86_64
    ports:
      - "22005:22005/udp"
      - "22006:22006"
      - "3434:3434"
  cef:
    build: ./cef
    restart: always
    env_file: docker.env
    ports:
      - 8080:8080
    depends_on:
      - server

