version: "3.8"
services:
  api:
    restart: always
    env_file: .env
    build: server
    tty: true
    ports:
      - "22005:22005/udp"
      - "22006:22006"
      - "3434:3434"
    depends_on:
      - cache
      - mongodb
      - cef
  cache:
    image: umudik/fookie-cache
    env_file: .env
    ports:
      - 2630:2630
  mongodb:
    image: mongo
    restart: always
    env_file: .env
    ports:
      - 27017:27017        
    volumes:
      - './data:/data/db'  
  cef:
    build: ./cef
    restart: always
    env_file: .env
    ports:
      - 8080:80

