module.exports = async function (ctx) {
    await ctx.model({
        mixin: ["entity", "cache"],
        name: 'vehicle',
        database: "mongodb",
        schema: {
            joaat: { type: "string", required: true },
            rotation: { type: "object" },
            owner: { relation: "character" },
            inventory: { relation: "inventory" },
            mod_spoiler: { type: "number", default: -1 },
            mod_front_bumper: { type: "number", default: -1 },
            mod_rear_bumper: { type: "number", default: -1 },
            mod_side_skirt: { type: "number", default: -1 },
            mod_exhaust: { type: "number", default: -1 },
            mod_frame: { type: "number", default: -1 },
            mod_grille: { type: "number", default: -1 },
            mod_hood: { type: "number", default: -1 },
            mod_fender: { type: "number", default: -1 },
            mod_right_fender: { type: "number", default: -1 },
            mod_roof: { type: "number", default: -1 },
            mod_engine: { type: "number", default: -1 },
            mod_brake: { type: "number", default: -1 },
            mod_transmission: { type: "number", default: -1 },
            mod_horn: { type: "number", default: -1 },
            mod_suspension: { type: "number", default: -1 },
            mod_armor: { type: "number", default: -1 },
            mod_turbo: { type: "number", default: -1 },
            mod_xenon: { type: "number", default: -1 },
            mod_front_wheels: { type: "number", default: -1 },
            mod_back_wheels: { type: "number", default: -1 },
            mod_plate_holder: { type: "number", default: -1 },
            mod_vanity_plate: { type: "number", default: -1 },
            mod_trim_design: { type: "number", default: -1 },
            mod_ornament: { type: "number", default: -1 },
            mod_dial_design: { type: "number", default: -1 },
            mod_steering_wheel: { type: "number", default: -1 },
            mod_shift_lever: { type: "number", default: -1 },
            mod_plaques: { type: "number", default: -1 },
            mod_speakers: { type: "number", default: -1 },
            mod_trunk: { type: "number", default: -1 },
            mod_hydraulic: { type: "number", default: -1 },
            mod_engine_block: { type: "number", default: -1 },
            mod_boost: { type: "number", default: -1 },
            mod_struts: { type: "number", default: -1 },
            mod_arch_cover: { type: "number", default: -1 },
            mod_aerial: { type: "number", default: -1 },
            mod_trim: { type: "number", default: -1 },
            mod_tank: { type: "number", default: -1 },
            mod_windows: { type: "number", default: -1 },
            mod_unknown: { type: "number", default: -1 },
            mod_livery: { type: "number", default: -1 },
            mod_plate: { type: "number", default: -1 },
            mod_window_tint: { type: "number", default: -1 },
            color1: { type: "array", default: [255, 255, 255] },
            color2: { type: "array", default: [255, 255, 255] },
            locked: { type: "boolean", default: false },
            alarm: { type: "boolean", default: false },
            ragemp_engine: { type: "boolean", default: false },
            ragemp_fuel: { type: "number", default: 100 },
        },
        lifecycle: {
            read: {
                role: ["everybody"],
            },
            update: {
                role: ["system"],
            },
            create: {
                role: ["system"],
            },
            delete: {
                role: ["system"],
            },
            schema: {
                role: ["everybody"],
            },
        }
    })
}



