name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RAGEMP_TEST_SERVER }}
          username: ${{ RAGEMP_TEST_HOST }}
          key:  ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: whoami
