name: Docker Image CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ RAGEMP_TEST_HOST }}
          key:  ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: whoami
